version: "3.8"
services:
  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./psql_history:/root/.psql_history
      - ./.psqlrc:/root/.psqlrc:ro

  redis:
    image: redis:6.2-alpine
    ports:
      - '63790:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
