version: "3.5"
services:
  database:
    container_name: postgres_container
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
  cache:
    image: redis:6.2-alpine
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes